name: Publish to JSR

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
          
      - name: Publish to JSR
        uses: denoland/jsr-publish@v1
        with:
          token: ${{ secrets.JSR_TOKEN }} 